import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Key } from 'react';

type Props = {
  items: Array<{id: Key, title: String}>;
};

export default function Home({ items }: Props) {
  const deleteItem = (id: Key) => {
    async function deleteTask() {
      const response = await fetch(`https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/deleteTaskById?itemId=${id}`, {method: 'DELETE'})
      const data = response.json();
      return data
    }
    deleteTask()
  }
  return (
    <>
      <Head>
        <title>Apiテスト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Apiテスト</h1>
        {items.map((item) => {return <div key={item.id}>{item.title} <button onClick={() => deleteItem(item.id)}>削除</button></div>})}
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const response = await fetch('https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/tasks');
  const data = await response.json();
  return {
    props: {
      items: data.tasks
    }
  }
}
