import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';

type Props = {
  items: Array<{id: string, title: string}>;
};

export default function Home({ items }: Props) {
  const [value, setValue] = useState('')
  // const [imgURL, setURL] = useState('')
  const router = useRouter()
  const deleteItem = (id: string) => {
    async function deleteTask() {
      const response = await fetch(`https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/deleteTaskById?itemId=${id}`, {method: 'DELETE'})
      const data = response.json();
      return data
    }
    deleteTask()
  }
  const addTask = (data: string) => {
    console.log('addTask呼ばれた')
    const requestBody = {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({title: data})
    }
    fetch('https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/tasks', requestBody)
    .then((response) => response.json()).then((data) => console.log(data))
  }
  // useEffect(()=>{
  //   fetch('https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/getImage')
  //   .then((response) => response.blob())
  //   .then((myBlob) => {
  //     const data = URL.createObjectURL(myBlob);
  //     setURL(data);
  //     console.log(myBlob)
  //   })
  // }, [])
  return (
    <>
      <Head>
        <title>Apiテスト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={'https://aws-lambda-images-418581597558.s3.ap-northeast-1.amazonaws.com/fortutorial.jpg'} alt={'サムネイル'} width={100} height={100} />
      <main className={styles.main}>
        <h1>Apiテスト</h1>
        <h2>タスク登録</h2>
        <input type="text" onChange={(e) => setValue(e.target.value)} />
        <button onClick={() => addTask(value)}>追加</button>
        <h3>タスク一覧</h3>
        {items.map((item) => {return <div key={item.id}><Link href={`/tasks/${item.id}`}>{item.title}</Link><button onClick={() => deleteItem(item.id)}>削除</button><button onClick={()=>router.push(`/tasks/${item.id}`)}>編集</button></div>})}
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const response = await fetch('https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/tasks');
  const data = await response.json();
  
  return {
    props: {
      items: data.tasks
    }
  }
}
