import Head from "next/head";
import { useState } from "react";

type ItemData = {id: {S: string}, title: {S: string}}

export default function ItemPage({itemData}: {itemData: ItemData}) {
  const [title, setTitle] = useState(`${itemData.title.S}`)
  const submit = (title: string) => {
    const body = {
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({title})
    }
    console.log(body.body)
    const data = fetch(`https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/updateTaskById?itemId=${itemData.id.S}`, body)
    .then((res) => res.json())
    console.log(data)
  }
  return(
    <>
      <Head>
        <title>{itemData.title.S}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{itemData.title.S}</h1>
        <input type="text" onChange={(e) => setTitle(e.target.value)} defaultValue={itemData.title.S}/>
        <button onClick={() => submit(title)}>更新</button>
      </main>
    </>
  )
}


export async function getStaticProps({
  params,
}: {
  params: { id: number };
}) {
  const id = params.id;
  const res = await fetch(
    `https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/getTaskById?itemId=${id}`
  )
  const itemData = await res.json()
  return {
    props: {
      itemData,
    },
  };
}

export async function getStaticPaths() {
  const getItems = await fetch(
    'https://gwp3bt9vq3.execute-api.ap-northeast-1.amazonaws.com/tasks'
  ).then((res) => res.json());
  const getPaths = getItems.tasks.map((item: { id: number }) => {
    return { params: { id: item.id.toString() } };
  });
  return {
    paths: getPaths,
    fallback: false,
  };
}
